### ISSUE TITLE
Status插件中的HTML文字会直接以文本形式输出

### ISSUE THREAD

**Issue by Gradua11y** [koishijs/koishi-plugin-imagify#1]
![_4Y4QXQ{(693@J2Y$L%CW@X_tmb](https://user-images.githubusercontent.com/80976109/234071051-1efe7c0d-a19f-4790-97ef-045e1bff35be.PNG)
后台没有报错之类的，插件使用的是status

**Comment by PatchouliEmoji** [comment]
同样的情况
![4TQA_3~RAO@2%E)0_) 7@V6_tmb](https://user-images.githubusercontent.com/95419554/236977421-cb3ec7c9-d5d7-4c0e-b356-bf6de6698b92.PNG)

**Comment by Lipraty** [comment]
fixed.
