### ISSUE TITLE
正常调用指令时文转图正常但是自动推送时会导致不发送

### ISSUE THREAD

**Issue by axlmly** [koishijs/koishi-plugin-imagify#5]
![Screenshot_2023-12-09-22-40-49-977_com.android.chrome.jpg](https://github.com/koishijs/koishi-plugin-imagify/assets/41771421/9919161b-f40b-483a-a73f-41e7d58a3171)

开启插件后例如kbot的动态监听和blive的直播推送都无法自动发送信息，但是手动可以，请问是不在预期吗？

**Comment by Lipraty** [comment]
这不是预期的，不过问题已定位，可以等待新版本。

**Comment by Lipraty** [comment]
已发 2.1.2 版本，可以等待插件市场收录后更新测试。

**Comment by axlmly** [comment]
> 已发 2.1.2 版本，可以等待插件市场收录后更新测试。

![IMG_20231210_060423.jpg](https://github.com/koishijs/koishi-plugin-imagify/assets/41771421/56b5424a-1090-4d3a-bc38-975faad6cdf1)

还是不行

**Comment by Lipraty** [comment]
草，发现没有打包修好的，现在应该是可以的了 2.1.3
