### ISSUE TITLE
更新koishi到4.17.2后会输出多余的空白图片

### ISSUE THREAD

**Issue by wang0yue** [koishijs/koishi-plugin-imagify#9]
如图，在小火箭更新到最新版后（koishi 4.17.2 imagify 2.2.7）
发送help等会输出多余的空白图片（第二张图会延迟约6秒发，沙盒结果同下图）使用koishi 4.17.10是正常的
![6cf5b194197b6175b1b223116f10fc09](https://github.com/user-attachments/assets/1701e690-8b5b-4fe8-bbcb-80b48a03fc24)
![97dd5312548a1459cf19a0bfd679e9fa](https://github.com/user-attachments/assets/2ca6e353-54ee-4a45-a02b-4938a338c551)

System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 7840HS w/ Radeon 780M Graphics     

Binaries:
    Node: 20.12.2
    Yarn: 4.1.1

Koishi:
    Core: 4.17.12
    Console: 5.28.4
    Koishi Desktop: 1.1.3

**Comment by Lipraty** [comment]
是仅 `/toutai` 这一个指令吗？还是所有指令都会这样？

看 koishi 4.17.11-4.17.12 的修改，似乎对消息元素有修改，这个我先看看吧

**Comment by wang0yue** [comment]
> 是仅 `/toutai` 这一个指令吗？还是所有指令都会这样？
> 
> 看 koishi 4.17.11-4.17.12 的修改，似乎对消息元素有修改，这个我先看看吧

/toutai会多两个空白，/help会多一个，其他的还没试

**Comment by Lipraty** [comment]
> /toutai会多两个空白，/help会多一个，其他的还没试

好，这几天我抽空复现一下

**Comment by Lipraty** [comment]
在 `2.2.9` 处理了空内容的边缘情况，应该不会输出多余的空白的了，可以更新更新
